# Generated by Django 3.2.7 on 2021-10-31 09:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import file.utils
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('folder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('file', models.FileField(upload_to=file.utils.get_file_path)),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.IntegerField()),
                ('file_type', models.CharField(max_length=255)),
                ('file_category', models.CharField(max_length=30)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Date Uploaded')),
                ('parent_folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='folder.folder')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-uploaded_at',),
            },
        ),
        migrations.CreateModel(
            name='Trash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trashed_at', models.DateTimeField(auto_now_add=True, verbose_name='Date Trashed')),
                ('file', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='file.file')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trashed_files', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FilePrivacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(choices=[('public', 'Public'), ('friends', 'Friends'), ('private', 'Private')], default='private', max_length=10)),
                ('link', models.CharField(max_length=255, null=True, unique=True)),
                ('file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='privacy', to='file.file')),
                ('shared_with', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
