# Generated by Django 3.2.7 on 2022-02-27 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0003_alter_file_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileQuality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality', models.CharField(choices=[('p144', '144p'), ('p240', '1240p'), ('p480', '480p'), ('p720', '720p'), ('p1080', '1080p')], default='p144', max_length=100)),
                ('converted_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file.file')),
                ('original_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualities', to='file.file')),
            ],
            options={
                'unique_together': {('original_file', 'quality', 'converted_file')},
            },
        ),
    ]
