# Generated by Django 3.2.7 on 2022-02-27 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0004_filequality'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filequality',
            options={'verbose_name_plural': 'File Qualities'},
        ),
        migrations.AlterField(
            model_name='filequality',
            name='quality',
            field=models.CharField(choices=[('144p', '144p'), ('240p', '1240p'), ('480p', '480p'), ('720p', '720p'), ('1080p', '1080p')], default='144p', max_length=100),
        ),
    ]
