# Generated by Django 3.2.7 on 2022-03-06 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0006_file_converted'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='filequality',
            unique_together={('original_file', 'quality', 'converted_file')},
        ),
    ]
