# Generated by Django 3.2.7 on 2022-03-07 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0007_alter_filequality_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='filequality',
            name='status',
            field=models.CharField(choices=[('converted', 'Converted'), ('processing', 'Processing'), ('failed', 'Failed')], default='processing', max_length=100),
        ),
    ]
