# Generated by Django 3.2.7 on 2022-03-07 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0009_alter_filequality_converted_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filequality',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('converted', 'Converted'), ('failed', 'Failed')], default='processing', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='filequality',
            unique_together={('original_file', 'quality')},
        ),
    ]
