# Generated by Django 3.2.7 on 2022-03-07 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0010_auto_20220307_0719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filequality',
            name='converted_file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='file.file'),
        ),
    ]
