# Generated by Django 3.2.7 on 2022-03-08 10:08

from django.db import migrations, models
import django.db.models.deletion
import file.utils


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0011_alter_filequality_converted_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFileProperties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.FileField(blank=True, max_length=500, upload_to=file.utils.get_video_cover_path)),
                ('quality', models.CharField(choices=[('144p', '144p'), ('240p', '1240p'), ('480p', '480p'), ('720p', '720p'), ('1080p', '1080p')], default='144p', max_length=100)),
                ('media_file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='file.file')),
            ],
        ),
        migrations.CreateModel(
            name='VideoSubtitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'EN'), ('ar', 'AR')], default='en', max_length=100)),
                ('subtitle_file', models.FileField(max_length=500, upload_to=file.utils.get_video_subtitle_path)),
                ('media_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtitles', to='file.mediafileproperties')),
            ],
        ),
    ]
