# Generated by Django 3.2.7 on 2022-03-09 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0012_mediafileproperties_videosubtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filequality',
            name='status',
            field=models.CharField(choices=[('converting', 'Converting'), ('converted', 'Converted'), ('failed', 'Failed')], default='processing', max_length=100),
        ),
    ]
