# Generated by Django 3.2.7 on 2022-03-16 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0015_alter_videosubtitle_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='converted',
        ),
        migrations.AddField(
            model_name='mediafileproperties',
            name='converted',
            field=models.BooleanField(default=False),
        ),
    ]
