# Generated by Django 3.2.7 on 2022-03-29 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0017_alter_mediafileproperties_quality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filequality',
            name='status',
            field=models.CharField(choices=[('converting', 'Converting'), ('converted', 'Converted'), ('failed', 'Failed')], default='converting', max_length=100),
        ),
        migrations.AlterField(
            model_name='mediafileproperties',
            name='quality',
            field=models.CharField(choices=[('144p', '144p'), ('240p', '240p'), ('360p', '360p'), ('480p', '480p'), ('720p', '720p'), ('1080p', '1080p')], default='144p', max_length=100),
        ),
    ]
