# Generated by Django 3.2.7 on 2022-04-11 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0019_alter_file_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'ordering': ('-uploaded_at',), 'permissions': (('can_download_file', 'Can Download File'), ('can_stream_media_files', 'Can Stream Media Files'))},
        ),
        migrations.AlterModelOptions(
            name='filequality',
            options={'permissions': (('can_convert_media_files', 'Can Convert Media Files'),), 'verbose_name_plural': 'File Qualities'},
        ),
        migrations.AlterModelOptions(
            name='trash',
            options={'permissions': (('can_add_files_to_trash', 'Can add Files to Trash'),)},
        ),
    ]
