# Generated by Django 3.2.7 on 2022-04-11 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0023_auto_20220411_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedfile',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file.file'),
        ),
    ]
