# Generated by Django 3.2.7 on 2022-04-13 06:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('file', '0024_alter_sharedfile_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedfilepermission',
            name='can_rename',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='sharedfile',
            unique_together={('file', 'shared_with_user')},
        ),
    ]
