# Generated by Django 3.2.7 on 2022-04-13 07:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('file', '0026_filesharingblocklist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filesharingblocklist',
            name='users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
