# Generated by Django 3.2.7 on 2022-04-14 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('file', '0031_auto_20220414_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedfile',
            name='object_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sharedfile',
            name='object_type',
            field=models.ForeignKey(default=1, limit_choices_to=models.Q(models.Q(('app_label', 'file'), ('model', 'file')), models.Q(('app_label', 'folder'), ('model', 'folder')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, related_name='shared_with', to='contenttypes.contenttype'),
            preserve_default=False,
        ),
    ]
