# Generated by Django 3.2.7 on 2022-04-14 10:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('file', '0032_auto_20220414_1245'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='uploader',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='sharedfile',
            unique_together={('shared_by', 'object_id', 'shared_with')},
        ),
        migrations.RemoveField(
            model_name='sharedfile',
            name='file',
        ),
    ]
