# Generated by Django 3.2.7 on 2022-04-14 10:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('file', '0033_auto_20220414_1252'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sharedfile',
            unique_together={('shared_by', 'object_type', 'object_id', 'shared_with')},
        ),
    ]
