# Generated by Django 3.2.7 on 2022-04-14 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0034_alter_sharedfile_unique_together'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SharedFilePermission',
            new_name='SharedObjectPermission',
        ),
    ]
