# Generated by Django 3.2.7 on 2022-04-14 11:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('file', '0035_rename_sharedfilepermission_sharedobjectpermission'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SharedFile',
            new_name='SharedObject',
        ),
    ]
