# Generated by Django 3.2.7 on 2022-04-14 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0036_rename_sharedfile_sharedobject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='file_category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='file',
            old_name='file_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='file',
            old_name='file_size',
            new_name='size',
        ),
        migrations.RenameField(
            model_name='file',
            old_name='file_type',
            new_name='type',
        ),
    ]
