# Generated by Django 3.2.7 on 2022-05-04 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0041_auto_20220417_1028'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'ordering': ('-uploaded_at',), 'permissions': (('can_download_file', 'Can Download File'), ('can_copy_file', 'Can Copy File'), ('can_move_file', 'Can Move File'), ('can_rename_file', 'Can Rename File'), ('can_stream_media_files', 'Can Stream Media Files'))},
        ),
        migrations.AlterModelOptions(
            name='sharedobject',
            options={'ordering': ['-created_at'], 'permissions': (('can_share_files', 'Can Share Files'), ('can_share_folders', 'Can Share Folders'))},
        ),
    ]
