# Generated by Django 3.2.7 on 2021-11-03 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folder', '0002_alter_folder_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='name',
            field=models.CharField(default='New Folder', max_length=20),
        ),
    ]
