# Generated by Django 3.2.7 on 2022-04-11 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('folder', '0003_alter_folder_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='folder',
            options={'ordering': ('-created_at',), 'permissions': (('can_download_folder', 'Can Download Folder'),)},
        ),
    ]
