# Generated by Django 3.2.7 on 2022-04-11 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('folder', '0004_alter_folder_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='folder',
            options={'ordering': ('-created_at',), 'permissions': (('can_download_folder', 'Can Download Folder'), ('can_rename_folder', 'Can Rename Folder'))},
        ),
    ]
