# Generated by Django 3.2.7 on 2022-04-18 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('folder', '0005_alter_folder_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='folder',
            options={'ordering': ('-created_at',), 'permissions': (('can_download_folder', 'Can Download Folder'), ('can_rename_folder', 'Can Rename Folder'), ('can_copy_folder', 'Can Copy Folder'), ('can_move_folder', 'Can Move Folder'))},
        ),
    ]
