# Generated by Django 3.2.7 on 2021-09-22 14:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uploader.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=uploader.models.get_file_path)),
                ('size', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Date Uploaded')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
