# Generated by Django 3.2.7 on 2021-10-16 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0002_alter_folder_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_type',
            field=models.CharField(max_length=255),
        ),
    ]
