# Generated by Django 3.2.7 on 2021-10-16 08:07

from django.db import migrations, models
import uploader.models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0003_alter_file_file_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to=uploader.models.get_file_path),
        ),
    ]
