# Generated by Django 3.2.7 on 2021-09-23 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0004_alter_file_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file_name',
            field=models.CharField(default='default', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='file',
            name='file_size',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
