# Generated by Django 3.2.7 on 2021-09-23 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0005_auto_20210923_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_size',
            field=models.IntegerField(max_length=255),
        ),
    ]
