# Generated by Django 3.2.7 on 2021-09-23 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0006_alter_file_file_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file_type',
            field=models.CharField(default='img', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='file',
            name='file_size',
            field=models.IntegerField(),
        ),
    ]
