# Generated by Django 3.2.7 on 2021-09-23 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0008_file_file_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'ordering': ('-uploaded_at',)},
        ),
    ]
