# Generated by Django 3.2.7 on 2021-09-26 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0010_trash'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='privacy',
            field=models.CharField(choices=[('public', 'Public'), ('friends', 'Friends'), ('private', 'Private')], default='public', max_length=10),
        ),
    ]
