# Generated by Django 3.2.7 on 2021-09-26 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0011_file_privacy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_name',
            field=models.CharField(max_length=255),
        ),
    ]
