# Generated by Django 3.2.7 on 2021-09-26 11:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('uploader', '0012_alter_file_file_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trash',
            name='files',
        ),
        migrations.AddField(
            model_name='trash',
            name='file',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='uploader.file'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trash',
            name='trashed_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date Trashed'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trash',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trash_files', to=settings.AUTH_USER_MODEL),
        ),
    ]
