# Generated by Django 3.2.7 on 2021-09-28 06:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('uploader', '0013_auto_20210926_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='trash',
            name='file',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='uploader.file'),
        ),
        migrations.AlterField(
            model_name='trash',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trashed_files', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uploader.folder')),
            ],
        ),
    ]
