# Generated by Django 3.2.7 on 2021-09-28 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0014_auto_20210928_0844'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='name',
            field=models.CharField(default='New Folder', max_length=30),
        ),
    ]
