# Generated by Django 3.2.7 on 2021-09-28 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0017_folder_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='files',
            field=models.ManyToManyField(blank=True, null=True, to='uploader.File'),
        ),
    ]
