# Generated by Django 3.2.7 on 2021-09-28 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0018_folder_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='files',
            field=models.ManyToManyField(blank=True, null=True, related_name='folder', to='uploader.File'),
        ),
    ]
