# Generated by Django 3.2.7 on 2021-09-29 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0020_folder_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='files',
        ),
        migrations.AddField(
            model_name='file',
            name='parent_folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='uploader.folder'),
        ),
    ]
