# Generated by Django 3.2.7 on 2021-09-29 11:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('uploader', '0022_alter_file_file_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='privacy',
        ),
        migrations.CreateModel(
            name='FilePrivacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(choices=[('public', 'Public'), ('friends', 'Friends'), ('private', 'Private')], default='private', max_length=10)),
                ('allowed_users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('file', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='uploader.file')),
            ],
        ),
    ]
