# Generated by Django 3.2.7 on 2021-09-29 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('uploader', '0023_auto_20210929_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileprivacy',
            name='allowed_users',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fileprivacy',
            name='file',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='privacy', to='uploader.file'),
        ),
    ]
