# Generated by Django 3.2.7 on 2021-10-01 09:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('uploader', '0024_auto_20210929_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileprivacy',
            name='allowed_users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
