# Generated by Django 3.2.7 on 2021-10-02 10:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('uploader', '0026_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileprivacy',
            name='allowed_users',
        ),
        migrations.AddField(
            model_name='fileprivacy',
            name='share_with',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
