# Generated by Django 3.2.7 on 2021-10-02 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0027_auto_20211002_1026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fileprivacy',
            old_name='share_with',
            new_name='shared_with',
        ),
    ]
