# Generated by Django 3.2.7 on 2021-10-02 15:23

from django.db import migrations, models
import django_clamd.validators
import uploader.models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0028_rename_share_with_fileprivacy_shared_with'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to=uploader.models.get_file_path, validators=[django_clamd.validators.validate_file_infection]),
        ),
    ]
