# Generated by Django 3.2.7 on 2021-10-03 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0029_alter_file_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='url',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='link',
            name='file',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='uploader.file'),
        ),
    ]
