# Generated by Django 3.2.7 on 2021-10-03 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0030_auto_20211003_1340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='url',
            new_name='link',
        ),
        migrations.DeleteModel(
            name='Link',
        ),
    ]
