# Generated by Django 3.2.7 on 2021-10-03 12:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('uploader', '0031_auto_20211003_1347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='link',
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=255)),
                ('file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='link', to='uploader.file')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
