# Generated by Django 3.2.7 on 2021-09-23 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='job_title',
            field=models.CharField(default='blank', max_length=30),
            preserve_default=False,
        ),
    ]
