# Generated by Django 3.2.7 on 2021-09-28 08:59

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_job_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='image',
            field=models.ImageField(default='hah', upload_to=accounts.models.get_profile_image_path),
            preserve_default=False,
        ),
    ]
