# Generated by Django 3.2.7 on 2021-10-23 14:01

from django.db import migrations, models
import django.db.models.deletion
import storage_package.models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_package', '0001_initial'),
        ('accounts', '0002_drivesettings_unlimited_storage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drivesettings',
            name='storage_limit',
        ),
        migrations.AddField(
            model_name='drivesettings',
            name='storage_package',
            field=models.ForeignKey(default=storage_package.models.StoragePackage.get_default_package, on_delete=django.db.models.deletion.CASCADE, related_name='package', to='storage_package.storagepackage'),
        ),
    ]
