# Generated by Django 3.2.7 on 2021-09-29 11:07

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_account_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='image',
            field=models.ImageField(default=accounts.models.get_default_profile_image, upload_to=accounts.models.get_profile_image_path),
        ),
    ]
