# Generated by Django 3.2.7 on 2021-09-29 13:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_account_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriveSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_limit', models.IntegerField()),
                ('storage_uploaded', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drive_sittings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
