# Generated by Django 3.2.7 on 2021-10-23 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_activity_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name_plural': 'Activities'},
        ),
        migrations.AlterModelOptions(
            name='drivesettings',
            options={'verbose_name_plural': 'Drive Settings'},
        ),
    ]
