# Generated by Django 3.2.7 on 2021-09-29 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_drivesettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drivesettings',
            options={'verbose_name_plural': 'DriveSettings'},
        ),
        migrations.AlterField(
            model_name='drivesettings',
            name='storage_limit',
            field=models.IntegerField(help_text='Storage in bytes.'),
        ),
        migrations.AlterField(
            model_name='drivesettings',
            name='storage_uploaded',
            field=models.IntegerField(help_text='Storage in bytes.'),
        ),
    ]
