# Generated by Django 3.2.7 on 2021-09-29 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210929_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivesettings',
            name='storage_limit',
            field=models.DecimalField(decimal_places=4, default=150, help_text='Storage in GB.', max_digits=255),
        ),
        migrations.AlterField(
            model_name='drivesettings',
            name='storage_uploaded',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Storage in GB.', max_digits=255),
        ),
    ]
