# Generated by Django 3.2.7 on 2021-10-24 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20211023_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='activity_text',
            field=models.TextField(default='None', max_length=50),
            preserve_default=False,
        ),
    ]
