# Generated by Django 3.2.7 on 2021-10-24 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_activity_activity_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='activity_text',
            new_name='object_name',
        ),
    ]
