# Generated by Django 3.2.7 on 2021-09-29 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_drivesettings_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drivesettings',
            options={},
        ),
    ]
