# Generated by Django 3.2.7 on 2021-10-30 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_rename_activity_text_activity_object_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Activity',
        ),
    ]
