# Generated by Django 3.2.7 on 2021-09-29 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20210929_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivesettings',
            name='storage_limit',
            field=models.FloatField(default=150, help_text='Storage in GB.'),
        ),
        migrations.AlterField(
            model_name='drivesettings',
            name='storage_uploaded',
            field=models.FloatField(default=0, help_text='Storage in GB.'),
        ),
    ]
