# Generated by Django 3.2.7 on 2021-10-03 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20210929_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivesettings',
            name='storage_limit',
            field=models.FloatField(default=15, help_text='Storage in GB.'),
        ),
    ]
