# Generated by Django 3.2.7 on 2021-10-04 07:23

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_drivesettings_storage_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.get_profile_image_path),
        ),
    ]
