# Generated by Django 3.2.7 on 2021-10-23 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoragePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('storage', models.FloatField(default=15, help_text='Storage in GB.')),
                ('duration', models.FloatField(help_text='Duration in months.', null=True)),
                ('price', models.FloatField(null=True)),
                ('default', models.BooleanField(default=False)),
            ],
        ),
    ]
