# Generated by Django 3.2.7 on 2021-10-23 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_package', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storagepackage',
            name='default',
            field=models.BooleanField(default=False, unique=True),
        ),
    ]
