# Generated by Django 3.2.7 on 2021-10-31 09:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import storage_package.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('storage_package', '0002_alter_storagepackage_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriveSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_uploaded', models.FloatField(default=0, help_text='Storage in GB.')),
                ('unlimited_storage', models.BooleanField(default=False)),
                ('storage_package', models.ForeignKey(default=storage_package.models.StoragePackage.get_default_package, on_delete=django.db.models.deletion.CASCADE, related_name='package', to='storage_package.storagepackage')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='drive_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Drive Settings',
            },
        ),
    ]
