# Generated by Django 3.2.7 on 2021-12-01 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivesettings',
            name='default_upload_privacy',
            field=models.CharField(choices=[('public', 'Public'), ('friends', 'Friends'), ('private', 'Private')], default='private', max_length=10),
        ),
    ]
