# Generated by Django 3.2.7 on 2022-04-05 08:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drive', '0002_drivesettings_default_upload_privacy'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompressedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip', models.FileField(max_length=500, upload_to='')),
                ('is_compressed', models.BooleanField(default=False)),
                ('compressed_at', models.DateTimeField(auto_now_add=True, verbose_name='Date Compressed')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compressed_files', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
