# Generated by Django 3.2.7 on 2022-04-05 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drive', '0003_compressedfile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compressedfile',
            options={'ordering': ['-compressed_at']},
        ),
        migrations.AlterField(
            model_name='compressedfile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='compressed_files', to=settings.AUTH_USER_MODEL),
        ),
    ]
