# Generated by Django 3.2.7 on 2022-04-05 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0004_auto_20220405_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='compressedfile',
            name='is_downloaded',
            field=models.BooleanField(default=False),
        ),
    ]
