# Generated by Django 3.2.7 on 2022-04-07 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0005_compressedfile_is_downloaded'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drivesettings',
            options={'permissions': (('can_erase_data', 'Can Erase Data'),), 'verbose_name_plural': 'Drive Settings'},
        ),
    ]
