# Generated by Django 3.2.7 on 2022-04-11 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0007_alter_drivesettings_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drivesettings',
            options={'permissions': (('can_erase_account_data', 'Can Erase Account Data'), ('can_compress_account_data', 'Can Compress Account Data')), 'verbose_name_plural': 'Drive Settings'},
        ),
    ]
